name: Deploy to Vercel Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_8VH7YGU0P5iBtrtqpcAfP18d
          vercel-project-id: prj_uXqynRPCuslPyFGO3n93XNq3xUYI
          vercel-args: '--prod'
